exp:
    image: oliverde8/mp-expansion
    volumes:
        - ./docker/data/UserData/:/var/maniaplanet/UserData/
    links:
        - mysql
        - dedicated

dedicated:
    image: oliverde8/mp-dedicated
    environment:
        MP_LOGIN: my_server1
        MP_PASSWORD: my_server1_password
        MP_PORT: 2350
        MP_TITLE: TmCanyon@nadeo
        MP_GAME_SETTINGS: MatchSettings/TMCanyonA.txt@nadeo
        MP_CONFIG: default.config.xml
    ports:
        - "2350:2350"
        - "2350:2350/udp"
    volumes:
        - ./docker/data/UserData/Maps:/var/maniaplanet/UserData/Maps
        - ./docker/data/UserData/Config:/var/maniaplanet/UserData/Config
        - ./docker/data/UserData/Scripts:/var/maniaplanet/UserData/Scripts

mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_DATABASE: expansion
        MYSQL_USER: root
        MYSQL_PASSWORD: ""
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
        - ./docker/data/mysql:/var/lib/mysql
